import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="min-h-full bg-neutral-950">
          <header className="absolute left-0 right-0 z-10">
            <nav className="bg-slate-800 px-4 py-12 md:bg-transparent">
              <div className="mx-auto flex max-w-6xl items-center">
                <Link href="/" className="flex-0">
                  <div className="flex">
                    <span className="flex items-center justify-center"></span>
                    <span className="mx-3 text-2xl">Jonathan Jauhari</span>
                  </div>
                </Link>
                <div className="flex flex-1 items-center justify-end">
                  <Link href="/blog" className="mx-2 block px-4 py-1 text-2xl">
                    Blog
                  </Link>
                  <Link
                    href="/projects"
                    className="mx-2 block px-4 py-1 text-2xl"
                  >
                    Projects
                  </Link>
                  <Link href="/about" className="mx-2 block px-4 py-1 text-2xl">
                    About
                  </Link>
                </div>
              </div>
            </nav>
          </header>
          <main className="flex">
            <div className="mx-auto max-w-4xl px-6 pt-40">{children}</div>
          </main>
          <footer className="mt-8">
            <div />
          </footer>
        </div>
      </body>
    </html>
  );
}
