import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="min-h-full bg-neutral-950">
          <header className="fixed left-0 right-0 z-10">
            <nav>
              <div>
                <Link href="/blog">blog</Link>
                <Link href="/projects">projects</Link>
                <Link href="/about">about</Link>
              </div>
            </nav>
          </header>
          <main className="flex">
            <div className="mb-auto mt-0 pt-16">{children}</div>
          </main>
          <footer className="mt-8">
            <div />
          </footer>
        </div>
      </body>
    </html>
  );
}
