// Reinventing CSS-in-JS...

export const proseClasses = [
  "max-w-none",
  "text-amber-100",
  "prose",
  "prose-lg",
  "prose-invert",
  "prose-stone",
  "prose-ol:max-w-prose",
  "prose-ol:mx-auto",
  "prose-ul:max-w-prose",
  "prose-ul:mx-auto",
  "prose-p:max-w-prose",
  "prose-p:mx-auto",
  "prose-blockquote:max-w-prose",
  "prose-blockquote:mx-auto",
  "prose-blockquote:text-amber-200",
  "prose-blockquote:border-l-amber-700",
  "prose-blockquote:border-l-4",
  "prose-headings:max-w-prose",
  "prose-headings:mx-auto",
  "prose-headings:text-teal-600",
  "prose-headings:font-normal",
  "prose-headings:font-serif",
  "prose-a:text-teal-600",
  "prose-a:decoration-dotted",
  "prose-a:underline-offset-4",
  "prose-a:decoration-2",
  "prose-a:decoration-teal-600",
  "hover:prose-a:decoration-amber-700",
  "hover:prose-a:text-teal-400",
  "focus:prose-a:decoration-solid",
  "focus:prose-a:decoration-amber-700",
  "focus:prose-a:text-teal-200",
  "prose-li:marker:text-amber-400",
  "prose-code:text-amber-200",
  "prose-code:font-normal",
  "prose-pre:mx-auto",
  "prose-strong:text-amber-200",
];

export const postLinkClasses = [
  "border-l-4",
  "border-transparent",
  "group-hover:border-dotted",
  "group-hover:border-amber-700",
  "group-hover:bg-stone-900",
  "group-focus:border-amber-700",
  "group-focus:border-solid",
];
